#!/bin/bash

# Function to display subdomain information
display_info() {
  domain=$1
  subdomain=$2
  result=$(dig ${subdomain}.${domain} | grep -A1 'ANSWER SECTION:')
  record_type=$(echo "${result}" | grep -o 'IN\s*[A-Z]*' | awk '{print $2}')
  destination=$(echo "${result}" | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+')

  echo "The subdomain ${subdomain} is a ${record_type} record and points to ${destination}"
}

# Main script
if [ $# -eq 1 ]; then
  # Display information for default subdomains
  display_info $1 "www"
  display_info $1 "lb-01"
  display_info $1 "web-01"
  display_info $1 "web-02"
elif [ $# -eq 2 ]; then
  # Display information for specified subdomain
  display_info $1 $2
else
  echo "Usage: $0 <domain> [subdomain]"
fi
