#!/bin/bash

# Check if an argument was passed
if [ $# -eq 0 ]; then
  # Display usage message and exit
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi

# Store the IP address in a variable
IP_ADDRESS=$1

# Ping the IP address 5 times
ping -c 5 $IP_ADDRESS

